version: 2

models:
  - name: dim_store
    columns:
      - name: store_key
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
