version: 2

models:
  - name: dim_store
    columns:
      - name: store_key
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: dim_destination
    columns:
      - name: destination_key
        tests:
          - unique
          - not_null
      - name: destination_name
        tests:
          - unique
          - not_null
      - name: channel
        tests:
          - not_null

  - name: dim_employee
    columns:
      - name: employee_key
        tests:
          - unique
          - not_null
      - name: employee_name
        tests:
          - unique
          - not_null
