version: 2

models:
  - name: dim_store
    columns:
      - name: store_key
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: dim_destination
    columns:
      - name: destination_key
        tests:
          - unique
          - not_null
      - name: destination_name
        tests:
          - unique
          - not_null
      - name: channel
        tests:
          - not_null

  - name: dim_employee
    columns:
      - name: employee_key
        tests:
          - unique
          - not_null
      - name: employee_name
        tests:
          - unique
          - not_null

  - name: dim_product
    columns:
      - name: product_key
        tests:
          - unique
          - not_null
      - name: product_name
        tests:
          - unique
          - not_null
      - name: product_canonical_name
        tests:
          - not_null
      - name: revenue_center_name
        tests:
          - not_null
          - accepted_values:
              values: ['Beverage', 'Food', 'Retail', 'Other']

  - name: dim_campaign
    columns:
      - name: campaign_key
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
